// web/src/pages/About.tsx
import { useEffect, useState } from "react";
import { CArticle } from "@/components/CArticle";
import { Comment } from "@/components/Comment";
import { articleDetailApi } from "@/service";

export default function About() {
  const [article, setArticle] = useState<any>({});
  useEffect(() => {
    (async () => {
      const a = await articleDetailApi({ url: "about" });
      setArticle(a);
      document.title = "关于我 - 無處告別";
    })();
  }, []);
  if (!article.id) return null;
  return (
    <div>
      <div className="mb-[10px]">
        <CArticle article={article} />
      </div>
      <Comment />
    </div>
  );
}

// src/pages/About.vue
<template>
    <div v-if="article.id">
        <div class="article-single">
            <CArticle :article="article"></CArticle>
        </div>
<!--        <Comment :postId="article.id"></Comment>-->
    </div>
</template>

<script>
  import {CArticle, Comment} from "../components";
  import {sync} from "../utils";
  import {articleDetailApi} from "../service";

  export default {
    name: 'About',
    components: {
      CArticle,
      Comment
    },
    data() {
      return {
        article: {},
      }
    },
    metaInfo: {
      title: "关于我"
    },
    methods: {
      load() {
        sync(async () => {
          this.article = await articleDetailApi({url: "about"})
        })
      }
    },
    mounted() {
      this.load()
    }
  }
</script>
