// web/src/pages/admin/AdminLink.tsx
import React, { useEffect, useState } from "react";
import {
  linkDeleteApi,
  linkListApi,
  linkCreateApi,
  linkUpdateApi,
} from "@/service";
import { BatchHandle } from "@/components/BatchHandle";

export default function AdminLink() {
  const [list, setList] = useState<any[]>([]);
  const [item, setItem] = useState<any>({});
  const loadList = async () => {
    const ret = await linkListApi({});
    setList(ret.list || []);
  };
  const editItem = (id: number) => setItem(list.find((i) => i.id === id));
  const deleteItem = async (id: number) => {
    if (confirm("确认要删除？")) {
      await linkDeleteApi({ id });
      loadList();
    }
  };
  const cancel = () => setItem({});
  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    const { id, name, url, desc } = item;
    if (id) await linkUpdateApi({ id, name, url, desc });
    else await linkCreateApi({ name, url, desc });
    setItem({});
    loadList();
  };
  useEffect(() => {
    loadList();
  }, []);
  return (
    <div className="clearfix">
      <h2>管理链接</h2>
      <div className="col-left">
        <div className="operate clearfix">
          <BatchHandle />
        </div>
        <table className="list">
          <tbody>
            <tr>
              <th style={{ width: 20 }}>&nbsp;</th>
              <th style={{ width: 80 }}>连接名</th>
              <th>地址</th>
              <th style={{ width: 80 }}>操作</th>
            </tr>
            {list.length === 0 && (
              <tr>
                <td colSpan={7} align="center">
                  还没有链接！
                </td>
              </tr>
            )}
            {list.length > 0 &&
              list.map((v) => (
                <tr key={v.id}>
                  <td>
                    <input type="checkbox" name="ids" value={v.id} />
                  </td>
                  <td>
                    <a href={v.url} target="_blank" rel="noreferrer">
                      {v.name}
                    </a>
                  </td>
                  <td>
                    <a href={v.url}>{v.url}</a>
                  </td>
                  <td>
                    <a
                      href="#"
                      onClick={(e) => {
                        e.preventDefault();
                        editItem(v.id);
                      }}
                    >
                      编辑
                    </a>
                    <span className="line">|</span>
                    <a
                      href="#"
                      onClick={(e) => {
                        e.preventDefault();
                        deleteItem(v.id);
                      }}
                    >
                      删除
                    </a>
                  </td>
                </tr>
              ))}
          </tbody>
        </table>
        <div className="operate clearfix">
          <BatchHandle />
        </div>
      </div>
      <div className="col-right" style={{ width: 250, paddingTop: 31 }}>
        <form className="vf" method="post" autoComplete="off" onSubmit={submit}>
          <p>
            <label className="label_input">链接名称</label>
            <input
              className="input_text"
              size={30}
              name="name"
              value={item.name || ""}
              onChange={(e) =>
                setItem((prev: any) => ({ ...prev, name: e.target.value }))
              }
            />
          </p>
          <p>
            <label className="label_input">链接地址</label>
            <input
              className="input_text"
              size={30}
              name="url"
              value={item.url || ""}
              onChange={(e) =>
                setItem((prev: any) => ({ ...prev, url: e.target.value }))
              }
            />
            <span className="hint">例如：http://fifsky.com/</span>
          </p>
          <p>
            <label className="label_input">链接描述</label>
            <textarea
              name="desc"
              rows={5}
              cols={30}
              value={item.desc || ""}
              onChange={(e) =>
                setItem((prev: any) => ({ ...prev, desc: e.target.value }))
              }
            ></textarea>
          </p>
          <p className="act">
            <button className="formbutton" type="submit">
              {item.id ? "修改" : "添加"}
            </button>
            {item.id && (
              <a
                className="ml10"
                href="#"
                onClick={(e) => {
                  e.preventDefault();
                  cancel();
                }}
              >
                取消
              </a>
            )}
          </p>
        </form>
      </div>
    </div>
  );
}

// src/pages/AdminLink.vue
<template>
    <div class="clearfix">
        <h2>管理链接</h2>

        <div class="col-left">
            <div class="operate clearfix">
                <BatchHandle/>
            </div>

            <table class="list">
                <tbody>
                <tr>
                    <th width="20">&nbsp;</th>
                    <th width="80">连接名</th>
                    <th>地址</th>
                    <th width="80">操作</th>
                </tr>
                <tr v-if="list.length === 0">
                    <td colspan="7" align="center">还没有链接！</td>
                </tr>
                <tr v-if="list.length > 0" v-for="(v,k) in list" :key="v.id">
                    <td><input type="checkbox" name="ids" :value="v.id"/></td>
                    <td><a :href="v.url" target="_blank">{{v.name}}</a></td>
                    <td><a :href="v.url">{{v.url}}</a></td>
                    <td><a href="javascript:void(0)" @click="editItem(v.id)">编辑</a><span class="line">|</span><a href="javascript:void(0)" @click="deleteItem(v.id)">删除</a>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="operate clearfix">
                <BatchHandle/>
            </div>
        </div>
        <div class="col-right" style="width: 250px; padding-top: 31px;">
            <form class="vf" method="post" autocomplete="off" @submit.prevent="submit">
                <p><label class="label_input">链接名称</label>
                    <input class="input_text" size="30" name="name"
                           v-model="item.name"></p>

                <p><label class="label_input">链接地址</label>
                    <input class="input_text" size="30" name="url"
                           v-model="item.url">
                    <span class="hint">例如：http://fifsky.com/</span>
                </p>
                <p>
                    <label class="label_input">链接描述</label>
                    <textarea name="desc" rows="5" cols="30" v-model="item.desc"></textarea>
                </p>
                <p class="act">
                    <button class="formbutton" type="submit">{{item.id ? '修改':'添加'}}</button><a v-show="item.id" class="ml10" href="javascript:void(0)" @click="cancel">取消</a>
                </p>
            </form>
        </div>
    </div>
</template>

<script>
  import {linkDeleteApi, linkListApi, linkCreateApi, linkUpdateApi} from "../service";
  import {BatchHandle} from "../components";
  import list from "../mixins/list"

  export default {
    name: "AdminLink",
    data() {
      return {
        listApi: linkListApi,
        createApi: linkCreateApi,
        updateApi: linkUpdateApi,
        deleteApi: linkDeleteApi
      }
    },
    mixins: [list],
    components: {
      BatchHandle
    },
    methods: {
      submit() {
        let {id, name,url,desc} = this.item
        this.triggerSubmit({id, name,url,desc})
      },
    },
    mounted() {
      this.loadList()
    }
  }
</script>

<style scoped>

</style>
