// web/src/pages/PostArticle.tsx
import React, { useEffect, useState } from "react";
import {
  articleDetailApi,
  articleCreateApi,
  articleUpdateApi,
  cateListApi,
} from "@/service";
import { useLocation, useNavigate, Link } from "react-router-dom";
import "@wangeditor/editor/dist/css/style.css";
import { Editor, Toolbar } from "@wangeditor/editor-for-react";
import type {
  IDomEditor,
  IEditorConfig,
  IToolbarConfig,
} from "@wangeditor/editor";
import { getApiUrl, getAccessToken } from "@/utils/common";

export default function PostArticle() {
  const [article, setArticle] = useState<any>({ type: 1 });
  const [cates, setCates] = useState<any[]>([]);
  const [editor, setEditor] = useState<IDomEditor | null>(null);

  const location = useLocation();
  const navigate = useNavigate();
  const params = new URLSearchParams(location.search);

  const toolbarConfig: Partial<IToolbarConfig> = {};
  const editorConfig: Partial<IEditorConfig> = {
    placeholder: "请输入内容...",
    MENU_CONF: {
      uploadImage: {
        server: getApiUrl("/api/admin/upload"),
        fieldName: "uploadFile",
        headers: { "Access-Token": getAccessToken() },
        withCredentials: false,
        maxFileSize: 10 * 1024 * 1024,
        allowedFileTypes: ["image/*"],
        onFailed(file: File, res: any) {
          alert(`${file.name} 上传失败` + (res.message || ""));
        },
        onError(file: File, err: any) {
          alert(`${file.name} 上传失败` + (err || ""));
        },
      },
    },
  };

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    const { id, cate_id, title, content, type, url } = article;
    if (!title || title.length === 0) {
      alert("标题不能为空");
      return;
    }
    if (!cate_id || cate_id < 1) {
      alert("请选择分类");
      return;
    }
    const data = { id, cate_id, title, content, type, url };
    if (id)
      await articleUpdateApi({
        id,
        cate_id: cate_id,
        title,
        content,
        type,
        url,
      });
    else await articleCreateApi(data);
    navigate("/admin/articles");
  };

  useEffect(() => {
    (async () => {
      if (params.get("id")) {
        const a = await articleDetailApi({ id: parseInt(params.get("id")!) });
        setArticle({ ...a, cate_id: a.cate_id });
      }
      const ret = await cateListApi({});
      setCates(ret.list || []);
      setArticle((prev: any) => ({
        ...prev,
        cate_id: prev.cate_id || ret.list?.[0]?.id || 0,
      }));
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => {
    return () => {
      if (editor) editor.destroy();
    };
  }, [editor]);

  return (
    <div id="articles">
      <h2>
        {article.id ? "编辑" : "撰写"}文章
        <Link to="/admin/articles">
          <i className="iconfont icon-undo" style={{ color: "#444" }}></i>
          返回列表
        </Link>
      </h2>
      <div className="message"></div>
      <form className="vf" method="post" autoComplete="off" onSubmit={submit}>
        <div className="clearfix">
          <div className="col-left">
            <p>
              <label className="label_input">标题</label>
              <input
                type="text"
                className="input_text"
                maxLength={200}
                size={50}
                name="title"
                value={article.title || ""}
                onChange={(e) =>
                  setArticle({ ...article, title: e.target.value })
                }
              />
            </p>
            <p>
              <label className="label_input">分类</label>
              {cates.length > 0 && (
                <select
                  name="cate_id"
                  value={article.cate_id || ""}
                  onChange={(e) =>
                    setArticle({ ...article, cate_id: Number(e.target.value) })
                  }
                >
                  {cates.map((v) => (
                    <option key={v.id} value={v.id}>
                      {v.name}
                    </option>
                  ))}
                </select>
              )}
            </p>
            {article.type == 2 && (
              <p>
                <label className="label_input">缩略名</label>
                <input
                  type="text"
                  className="input_text"
                  maxLength={200}
                  size={50}
                  name="url"
                  value={article.url || ""}
                  onChange={(e) =>
                    setArticle({ ...article, url: e.target.value })
                  }
                />
                <span className="hint">
                  页面的URL名称，如红色部分http://domain.com/
                  <span style={{ color: "red" }}>about</span>
                </span>
              </p>
            )}
          </div>
          <div className="col-right">
            <p>
              <label className="label_input">类型</label>
              <input
                className="input_check"
                name="type"
                type="radio"
                checked={article.type === 1}
                onChange={() => setArticle({ ...article, type: 1 })}
              />
              文章
              <input
                className="input_check"
                name="type"
                type="radio"
                checked={article.type === 2}
                onChange={() => setArticle({ ...article, type: 2 })}
              />
              页面
            </p>
          </div>
        </div>
        <div id="editor">
          <div style={{ border: "1px solid #ddd" }}>
            <Toolbar
              editor={editor}
              defaultConfig={toolbarConfig}
              mode="default"
              style={{ borderBottom: "1px solid #ddd" }}
            />
            <Editor
              style={{ height: 500, overflowY: "hidden" }}
              defaultConfig={editorConfig}
              value={article.content || ""}
              onCreated={(ed: IDomEditor) => setEditor(ed)}
              onChange={(ed: IDomEditor) =>
                setArticle({ ...article, content: ed.getHtml() })
              }
              mode="default"
            />
          </div>
        </div>
        <p className="act">
          <input className="formbutton" type="submit" value="发布" />
          <a
            id="_save_draft"
            href="#"
            className="ml10"
            onClick={(e) => e.preventDefault()}
          >
            保存草稿
          </a>
        </p>
      </form>
    </div>
  );
}

// src/pages/PostArticle.vue
<template>
  <div id="articles">
    <h2>
      {{ article.id ? "编辑" : "撰写" }}文章
      <router-link to="/admin/articles"
        ><i class="iconfont icon-undo" style="color: #444"></i
        >返回列表</router-link
      >
    </h2>
    <div class="message"></div>
    <form class="vf" method="post" autocomplete="off" @submit.prevent="submit">
      <div class="clearfix">
        <div class="col-left">
          <p>
            <label class="label_input">标题</label>
            <input
              type="text"
              class="input_text"
              maxlength="200"
              size="50"
              name="title"
              v-model="article.title"
            />
          </p>
          <p>
            <label class="label_input">分类</label>

            <select
              name="cate_id"
              v-model="article.cate_id"
              v-if="cates.length"
            >
              <option v-for="(v, k) in cates" :key="v.id" :value="v.id">{{
                v.name
              }}</option>
            </select>
          </p>
          <p v-show="article.type == 2">
            <label class="label_input">缩略名</label>
            <input
              type="text"
              class="input_text"
              maxlength="200"
              size="50"
              name="url"
              v-model="article.url"
            />
            <span class="hint"
              >页面的URL名称，如红色部分http://domain.com/<span
                style="color: red;"
                >about</span
              ></span
            >
          </p>
        </div>
        <div class="col-right">
          <p>
            <label class="label_input">类型</label>
            <input
              class="input_check"
              name="type"
              type="radio"
              v-model="article.type"
              value="1"
            />
            文章
            <input
              class="input_check"
              name="type"
              type="radio"
              v-model="article.type"
              value="2"
            />
            页面
            <br />
            <!--<select name="power">-->
            <!--<option value="1">公开</option>-->
            <!--<option value="2">私密</option>-->
            <!--</select>-->
            <!--<input style="display: none" type="text" class="input_text" name="post_password"-->
            <!--value="" size="20"/>-->
          </p>
        </div>
      </div>
      <div id="editor"></div>
      <p class="act">
        <input class="formbutton" type="submit" value="发布" /><a
          id="_save_draft"
          href="javascript:void(0)"
          class="ml10"
          >保存草稿</a
        >
      </p>
    </form>
  </div>
</template>

<script>
import { getAccessToken, getApiUrl, sync } from "../utils";
import {
  articleDetailApi,
  articleCreateApi,
  articleUpdateApi,
  cateListApi,
} from "../service";
import { mapState } from "vuex";
import "highlight.js/styles/atelier-lakeside-light.css";
import WangEditor from "wangeditor";

export default {
  name: "PostArticle",
  data() {
    return {
      article: {
        type: 1,
      },
      cates: [],
      editor: "", //保存simditor对象
    };
  },
  computed: {
    ...mapState(["userInfo"]),
  },
  methods: {
    submit() {
      let { id, cate_id, title, content, type, url } = this.article;

      if (title.length === 0) {
        this.$message.success("标题不能为空");
      }

      if (cate_id < 1) {
        this.$message.success("请选择分类");
      }

      let data = { id, cate_id, title, content, type, url };
      sync(async () => {
        let ret = await (id ? articleUpdateApi : articleCreateApi)(data);
        this.$router.push("/admin/articles");
      });
    },
    createEditor() {
      const editor = new WangEditor("#editor");
      editor.config.uploadImgMaxSize = 3 * 1024 * 1024;
      editor.config.uploadImgMaxLength = 5;
      editor.config.uploadImgServer = "https://api.fifsky.com/api/admin/upload";
      editor.config.uploadFileName = "uploadFile";
      editor.config.uploadImgHeaders = {
        "Access-Token": getAccessToken(),
      };
      editor.config.uploadImgHooks = {
        error: function(xhr, editor) {
          // 图片上传出错时触发
          // xhr 是 XMLHttpRequst 对象，editor 是编辑器对象
          console.log(xhr);
        },
      };
      editor.config.onchange = (newHtml) => {
        this.article.content = newHtml;
      };
      editor.create();
      this.editor = editor;
    },
  },
  mounted() {
    this.createEditor();
    sync(async () => {
      if (this.$route.query && this.$route.query.id) {
        this.article = await articleDetailApi({
          id: parseInt(this.$route.query.id),
        });
        this.editor.txt.html(this.article.content);
      }
      let ret = await cateListApi();
      this.cates = ret.list;
      this.article.cate_id = this.article.cate_id || this.cates[0].id;
    });
  },
  beforeDestroy() {
    // 销毁编辑器
    this.editor.destroy();
    this.editor = null;
  },
};
</script>

<style>
#editor pre code {
  background-color: #ebf8ff;
  color: #516d7b;
  overflow: visible;
}

#editor .w-e-toolbar .w-e-menu {
  height: 38px !important;
  width: 38px !important;
}
#editor .w-e-text p {
  font-size: 14px !important;
}
</style>
