// web/src/components/AdminLayout.tsx
import { useEffect } from "react";
import { Outlet, useLocation, Link, useNavigate } from "react-router";
import { CHeader } from "./CHeader";
import { CFooter } from "./CFooter";
import { useStore } from "@/store/context";
import { getAccessToken } from "@/utils/common";

export function AdminLayout() {
  const userInfo = useStore((s) => s.userInfo);
  const currentUserAction = useStore((s) => s.currentUserAction);
  const isLogin = !!userInfo.id;
  const location = useLocation();
  const navigate = useNavigate();

  const isPage = (...paths: string[]) =>
    paths.some((p) => location.pathname === p);

  useEffect(() => {
    if (getAccessToken()) {
      (async () => {
        try {
          await currentUserAction();
        } catch {
          navigate("/login");
        }
      })();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!getAccessToken()) navigate("/login");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [location.pathname]);

  return (
    <div id="container">
      <CHeader />
      {isLogin && (
        <div className="admin">
          <div className="tabs">
            <ul>
              <li>
                <Link
                  to="/admin/index"
                  className={isPage("/admin/index") ? "active" : ""}
                >
                  设置
                </Link>
              </li>
              <li>
                <Link
                  to="/admin/articles"
                  className={
                    isPage("/admin/articles", "/admin/post/article")
                      ? "active"
                      : ""
                  }
                >
                  文章
                </Link>
              </li>
              <li>
                <Link
                  to="/admin/comments"
                  className={isPage("/admin/comments") ? "active" : ""}
                >
                  评论
                </Link>
              </li>
              <li>
                <Link
                  to="/admin/moods"
                  className={isPage("/admin/moods") ? "active" : ""}
                >
                  心情
                </Link>
              </li>
              <li>
                <Link
                  to="/admin/cates"
                  className={isPage("/admin/cates") ? "active" : ""}
                >
                  分类
                </Link>
              </li>
              <li>
                <Link
                  to="/admin/links"
                  className={isPage("/admin/links") ? "active" : ""}
                >
                  链接
                </Link>
              </li>
              <li>
                <Link
                  to="/admin/remind"
                  className={isPage("/admin/remind") ? "active" : ""}
                >
                  提醒
                </Link>
              </li>
              <li>
                <Link
                  to="/admin/users"
                  className={isPage("/admin/users") ? "active" : ""}
                >
                  用户
                </Link>
              </li>
            </ul>
          </div>
          <div id="content">
            <Outlet />
          </div>
        </div>
      )}
      <CFooter />
    </div>
  );
}

// src/components/AdminLayout.vue
<template>
    <div id="container">
        <CHeader/>
        <div class="admin" v-if="isLogin">
            <div class="tabs">
                <ul>
                    <li><router-link to="/admin/index" :class="{active:isPage('/admin/index')}">设置</router-link></li>
                    <li><router-link to="/admin/articles" :class="{active:isPage('/admin/articles','/admin/post/article')}">文章</router-link></li>
                    <li><router-link to="/admin/comments" :class="{active:isPage('/admin/comments')}">评论</router-link></li>
                    <li><router-link to="/admin/moods" :class="{active:isPage('/admin/moods')}">心情</router-link></li>
                    <li><router-link to="/admin/cates" :class="{active:isPage('/admin/cates')}">分类</router-link></li>
                    <li><router-link to="/admin/links" :class="{active:isPage('/admin/links')}">链接</router-link></li>
                    <li><router-link to="/admin/remind" :class="{active:isPage('/admin/remind')}">提醒</router-link></li>
                    <li><router-link to="/admin/users" :class="{active:isPage('/admin/users')}">用户</router-link></li>
                </ul>
            </div>
            <div id="content">
                <router-view/>
            </div>
        </div>
        <CFooter/>
    </div>
</template>

<script>

  import {mapActions,mapGetters} from "vuex"
  import {CFooter, CHeader} from './index'
  import {getAccessToken, sync} from "../utils";

  export default {
    name: 'AdminLayout',
    components: {
      CHeader,
      CFooter,
    },
    computed:{
      ...mapGetters(["isLogin"])
    },
    methods: {
      ...mapActions(["currentUserAction"]),
      isPage: function () {
        let is = false
        for (let i = 0; i < arguments.length; i++) {
          if(this.$route.path === arguments[i]){
            is = true
            break
          }
        }
        return is
      },
    },
    mounted() {
      if(getAccessToken()) {
        sync(async () => {
          try {
            await this.currentUserAction()
          } catch (e) {
            this.$router.push("/login")
          }
        })
      }
    },
    beforeRouteEnter(to, form, next) {
      if (!getAccessToken()) {
          next("/login")
      } else {
          next()
      }
    }
  }
</script>
<style>

</style>
