// web/src/components/CHeader.tsx
import { Link, useNavigate } from "react-router";
import { useStore } from "@/store/context";

export function CHeader() {
  const userInfo = useStore((s) => s.userInfo);
  const setUserInfo = useStore((s) => s.setUserInfo);
  const isLogin = !!userInfo.id;
  const navigate = useNavigate();
  const logOut = () => {
    localStorage.removeItem("access_token");
    setUserInfo({});
    navigate("/");
  };
  return (
    <div id="header" className="flex items-center justify-between">
      <h1>
        <Link to="/">
          <img
            className="inline-block"
            alt="首页"
            src="/assets/images/logo.png"
          />
          <span>首页</span>
        </Link>
      </h1>
      <div id="navigation" className="inline-flex items-center">
        <ul className="flex items-center">
          <li>
            <Link to="/">首页</Link>
          </li>
          <li>
            <a
              href="https://github.com/fifsky"
              target="_blank"
              rel="noreferrer"
            >
              Github
            </a>
          </li>
          <li>
            <a href="https://gist.github.com/fifsky">技术</a>
          </li>
          <li>
            <Link to="/about">关于</Link>
          </li>
          <li>
            <a href="https://caixudong.com">简历</a>
          </li>
          {isLogin && (
            <li>
              <Link to="/admin/index">管理中心</Link>
            </li>
          )}
          {isLogin && (
            <li>
              <a
                href="#"
                onClick={(e) => {
                  e.preventDefault();
                  logOut();
                }}
              >
                退出
              </a>
            </li>
          )}
          {!isLogin && (
            <li>
              <Link to="/login">登录</Link>
            </li>
          )}
        </ul>
      </div>
    </div>
  );
}

// src/components/CHeader.vue
<template>
    <div id="header" class="clearfix">
        <h1>
            <router-link to="/"><img alt=首页 src="../assets/images/logo.png"><span>首页</span></router-link>
        </h1>

        <div id="navigation">
            <ul>
                <li><router-link to="/">首页</router-link></li>
                <li><a href="https://github.com/fifsky" target="_blank">Github</a></li>
                <li><a href="https://gist.github.com/fifsky">技术</a></li>
                <li><router-link to="/about">关于</router-link></li>
                <li><a href="https://caixudong.com">简历</a></li>
                <li><router-link to="/admin/index" v-if="isLogin">管理中心</router-link></li>
                <li><a v-if="isLogin" @click="logOut">退出</a></li>
                <li><router-link to="/login" v-if="!isLogin">登录</router-link></li>
            </ul>
        </div>
    </div>
</template>

<script>
  import {mapGetters,mapMutations} from "vuex"

  export default {
    name: "CHeader",
    computed:{
      ...mapGetters(["isLogin"])
    },
    methods:{
      ...mapMutations(["setUserInfo"]),
      logOut () {
        localStorage.removeItem('access_token')
        this.setUserInfo({})
        this.$router.push('/')
      },
    }
  }
</script>
