// web/src/components/SidebarList.tsx
import { useEffect, useState } from "react";
import { Link } from "react-router";
import { archiveApi, cateAllApi, linkAllApi, newCommentApi } from "@/service";

const apiMap = { cateAllApi, newCommentApi, archiveApi, linkAllApi };

export function SidebarList({
  title,
  api,
}: {
  title: string;
  api: keyof typeof apiMap;
}) {
  const [items, setItems] = useState<{ url: string; content: string }[]>([]);
  useEffect(() => {
    (async () => {
      const data = await apiMap[api]();
      setItems(data.list || []);
    })();
  }, [api]);
  return (
    <div className="sect">
      <h2>{title}</h2>
      <ul className="tlist">
        {items.map((v, k) => (
          <li key={k}>
            {v.url && v.url.startsWith("http") ? (
              <a target="_blank" href={v.url} rel="noreferrer">
                {v.content}
              </a>
            ) : (
              <Link to={v.url}>{v.content}</Link>
            )}
          </li>
        ))}
      </ul>
    </div>
  );
}

// src/components/SidebarList.vue
<template>
    <div class="sect">
        <h2>{{title}}</h2>
        <ul class="tlist">
            <li v-for="(v,k) in items" :key="k">
                <a v-if="v.url && v.url.substr(0, 4) === 'http'" target="_blank" :href="v.url">{{v.content}}</a>
                <router-link :to="v.url" v-else>{{v.content}}</router-link>
            </li>
        </ul>
    </div>
</template>

<script>
  import {cateAllApi,newCommentApi,archiveApi,linkAllApi} from "../service"
  import {sync} from "../utils";

  const apiMap = {
    cateAllApi,newCommentApi,archiveApi,linkAllApi
  }

  export default {
    name: "SidebarList",
    props: ["title", "api"],
    data() {
      return {
        items: {}
      }
    },
    mounted() {
      sync(async () => {
        this.items = await apiMap[this.api]()
      })
    }
  }
</script>
