// web/src/components/Sidebar.tsx
import React, { useEffect } from "react";
import { useNavigate, useLocation } from "react-router";
import { useStore } from "@/store/context";
import { SidebarList } from "./SidebarList";
import { Calendar } from "./Calendar";
import {
  InputGroup,
  InputGroupInput,
  InputGroupAddon,
} from "@/components/ui/input-group";
import { Search } from "lucide-react";

export function Sidebar() {
  const keyword = useStore((s) => s.keyword);
  const setKeyword = useStore((s) => s.setKeyword);
  const navigate = useNavigate();
  const location = useLocation();
  const changeKeyword = (e: React.ChangeEvent<HTMLInputElement>) => {
    setKeyword(e.target.value);
  };
  const onKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      navigate({
        pathname: "/search",
        search: `?keyword=${encodeURIComponent(keyword)}`,
      });
    }
  };
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    setKeyword(params.get("keyword") || "");
  }, [location.search]);
  return (
    <div id="sidebar">
      <div className="sect" id="search">
        <InputGroup>
          <InputGroupInput
            placeholder="搜索..."
            name="keyword"
            value={keyword}
            onChange={changeKeyword}
            onKeyDown={onKeyDown}
          />
          <InputGroupAddon>
            <Search />
          </InputGroupAddon>
        </InputGroup>
      </div>
      <Calendar />
      <SidebarList title="文章分类" api="cateAllApi" />
      <SidebarList title="历史存档" api="archiveApi" />
      <SidebarList title="我关注的" api="linkAllApi" />
      <div>
        <i className="iconfont icon-rss" style={{ color: "orange" }}></i>
        <a
          className="pl-[5px]"
          href="https://api.fifsky.com/feed.xml"
          target="_blank"
          rel="noreferrer"
        >
          订阅我的消息
        </a>
      </div>
    </div>
  );
}

// src/components/Sidebar.vue
<template>
    <div id="sidebar">
        <div class="sect" id="search">
            <form id="searchpanel" method="get" @submit.prevent="submit">
                <p>
                    <input class="input_text" type="text" name="keyword" @change="changeKeyword" :value="keyword"/>&nbsp;<input
                        class="formbutton" type="submit" value="搜索"/>
                </p>
            </form>
        </div>

        <Calendar/>
        <SidebarList title="文章分类" api="cateAllApi"></SidebarList>
        <SidebarList title="历史存档" api="archiveApi"></SidebarList>
<!--        <SidebarList title="最新评论" api="newCommentApi"></SidebarList>-->
        <SidebarList title="我关注的" api="linkAllApi"></SidebarList>

        <div class="rss">
            <i class="iconfont icon-feed" style="color: orangered"></i><a href="https://fifsky.com/feed.xml" target="_blank">订阅我的消息</a>
        </div>
    </div>
</template>

<script>
    import SidebarList from "./SidebarList";
    import Calendar from "./Calendar";
    import {mapState,mapMutations} from "vuex"

    export default {
        name: "Sidebar",
        components: {
            SidebarList,
            Calendar
        },
        computed:{
            ...mapState(['keyword'])
        },
        methods: {
            ...mapMutations(['setKeyword']),
            submit: function () {
                this.$router.push({name: 'search', query: {keyword: this.keyword}})
            },
            changeKeyword(e){
                this.setKeyword(e.target.value)
            }
        },
        created(){
            this.setKeyword(this.$route.query.keyword)
        }
    }
</script>
