// src/pages/AdminComment.vue
<template>
    <div>
        <h2>管理评论</h2>

        <div class="operate clearfix">
            <BatchHandle/>
        </div>

        <table class="list">
            <tbody>
            <tr>
                <th width="20">&nbsp;</th>
                <th width="150">文章</th>
                <th width="60">昵称</th>
                <th>评论</th>
                <th width="80">IP</th>
                <th width="130">日期</th>
                <th width="80">操作</th>
            </tr>
            <tr v-if="list.length === 0">
                <td colspan="7" align="center">还没有评论！</td>
            </tr>
            <tr v-if="list.length > 0" v-for="(v,k) in list" :key="v.id">
                <td><input type="checkbox" name="ids" :value="v.id"/></td>
                <td><a :href="(v.type === 2 ? v.url : '/article' + v.id)+'#comments'"
                                           target="_blank">{{ v.article_title }}</a></td>
                <td>{{v.name}}</td>
                <td>{{ v.content }}</td>
                <td>{{ v.ip }}</td>
                <td>{{ v.created_at | formatDate('YYYY-MM-DD HH:mm') }}</td>
                <td><a href="javascript:void(0)" @click="deleteItem(v.id)">删除</a></td>
            </tr>
            </tbody>
        </table>
        <div class="operate clearfix">
            <BatchHandle/>
            <Paginate
                    v-model="page"
                    :page-count="pageTotal"
                    :click-handler="changePage"
                    :prev-text="'<上一页'"
                    :next-text="'下一页>'"
                    :container-class="'paginator'">
            </Paginate>
        </div>
    </div>
</template>

<script>
  import {commentAdminListApi,commentDeleteApi} from "../service";
  import Paginate from 'vuejs-paginate'
  import {BatchHandle} from "../components";
  import list from "../mixins/list"

  export default {
    name: "AdminComment",
    data() {
      return {
        listApi:commentAdminListApi,
        deleteApi:commentDeleteApi,
      }
    },
    mixins: [list],
    components: {
      Paginate,
      BatchHandle
    },
    mounted() {
      this.loadList()
    }
  }
</script>

<style scoped>

</style>

// web/src/pages/AdminComment.tsx
import { useEffect, useState } from "react";
import { commentAdminListApi, commentDeleteApi } from "@/service";
import { BatchHandle } from "@/components/BatchHandle";
import { Paginate } from "@/components/Paginate";

export function AdminComment() {
  const [list, setList] = useState<any[]>([]);
  const [pageTotal, setPageTotal] = useState(0);
  const [page, setPage] = useState(1);
  const loadList = async () => {
    const ret = await commentAdminListApi({ page });
    setList(ret.list || []);
    setPageTotal(ret.page_total || 0);
  };
  const deleteItem = async (id: number) => {
    if (confirm("确认要删除？")) {
      await commentDeleteApi({ id });
      loadList();
    }
  };
  useEffect(() => {
    loadList();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page]);
  return (
    <div>
      <h2>管理评论</h2>
      <div className="operate clearfix">
        <BatchHandle />
      </div>
      <table className="list">
        <tbody>
          <tr>
            <th style={{ width: 20 }}>&nbsp;</th>
            <th style={{ width: 150 }}>文章</th>
            <th style={{ width: 60 }}>昵称</th>
            <th>评论</th>
            <th style={{ width: 80 }}>IP</th>
            <th style={{ width: 130 }}>日期</th>
            <th style={{ width: 80 }}>操作</th>
          </tr>
          {list.length === 0 && (
            <tr>
              <td colSpan={7} align="center">
                还没有评论！
              </td>
            </tr>
          )}
          {list.length > 0 &&
            list.map((v: any) => (
              <tr key={v.id}>
                <td>
                  <input type="checkbox" name="ids" value={v.id} />
                </td>
                <td>
                  <a
                    href={`${
                      v.type === 2 ? v.url : "/article" + v.id
                    }#comments`}
                    target="_blank"
                    rel="noreferrer"
                  >
                    {v.article_title}
                  </a>
                </td>
                <td>{v.name}</td>
                <td>{v.content}</td>
                <td>{v.ip}</td>
                <td>{new Date(v.created_at).toLocaleString()}</td>
                <td>
                  <a
                    href="#"
                    onClick={(e) => {
                      e.preventDefault();
                      deleteItem(v.id);
                    }}
                  >
                    删除
                  </a>
                </td>
              </tr>
            ))}
        </tbody>
      </table>
      <div className="operate clearfix">
        <BatchHandle />
        <Paginate page={page} pageTotal={pageTotal} onChange={setPage} />
      </div>
    </div>
  );
}
