// src/pages/ArticleList.vue
<template>
    <div>
        <div class="articles" v-for="(v,k) in list" :key="k">
            <CArticle :article="v"></CArticle>
            <div class="post-meta">
<!--                <span v-if="v.comment_num === 0">暂无评论</span><span-->
<!--                    v-if="v.comment_num > 0">评论({{v.comment_num}})</span><span class="line">|</span>-->
<!--                <router-link-->
<!--                        :to="'/article/'+v.id">查看更多&gt;&gt;-->
<!--                </router-link>-->
            </div>
        </div>
        <Paginate
                v-model="page"
                :page-count="pageTotal"
                :click-handler="changePage"
                :prev-text="'<上一页'"
                :next-text="'下一页>'"
                :container-class="'paginator'">
        </Paginate>
    </div>
</template>

<script>
  import {sync} from "../utils";
  import {articleListApi} from "../service";
  import {mapMutations, mapState} from "vuex"
  import {CArticle} from "../components";
  import Paginate from 'vuejs-paginate'

  export default {
    name: 'ArticleList',
    components: {
      CArticle,
      Paginate
    },
    data() {
      return {
        list: [],
        pageTotal: 0,
        page: 1
      }
    },
    methods: {
      ...mapMutations(['setKeyword']),
      loadList() {
        if (this.$route.query.page) {
          this.page = parseInt(this.$route.query.page)
        }else{
          this.page = 1
        }
        let data = {...this.$route.params, ...this.$route.query}
        data.page = this.page
        data.type = 1
        sync(async () => {
          let ret = await articleListApi(data)
          this.list = ret.list
          this.pageTotal = ret.page_total
        })
      },
      changePage(pageNum) {
        this.page = pageNum
        let q = {...this.$route.query}
        q.page = pageNum
        this.$router.push({path:this.$router.path,query:q})
      }
    },
    computed: {
      ...mapState(['keyword'])
    },
    mounted(){
      if (this.$route.path !== '/search') {
        this.setKeyword('')
      }
      this.loadList()
    }
  }
</script>

// web/src/pages/ArticleList.tsx
import { useEffect, useState } from "react";
import { useLocation, useNavigate, useParams } from "react-router";
import { CArticle } from "@/components/CArticle";
import { Pagination } from "@/components/Pagination";
import { articleListApi } from "@/service";
import { useStore } from "@/store/context";
import { usePrismHighlight } from "@/hooks";
import { ArticleItem, ArticleListRequest } from "@/types/openapi";

export default function ArticleList() {
  const [list, setList] = useState<ArticleItem[]>([]);
  const [pageTotal, setPageTotal] = useState(0);
  const [page, setPage] = useState(1);
  const location = useLocation();
  const navigate = useNavigate();
  const params = useParams();
  const setKeyword = useStore((s) => s.setKeyword);

  const loadList = async () => {
    const q = new URLSearchParams(location.search);
    const currentPage = q.get("page") ? parseInt(q.get("page")!) : 1;
    setPage(currentPage);
    const data: ArticleListRequest = {
      ...params,
      keyword: q.get("keyword") || "",
      page: currentPage,
      type: 1,
    };
    const ret = await articleListApi(data);
    setList(ret.list || []);
    setPageTotal(ret.page_total || 0);
  };

  const changePage = (p: number) => {
    setPage(p);
    const q = new URLSearchParams(location.search);
    q.set("page", String(p));
    navigate({ pathname: location.pathname, search: q.toString() });
  };

  useEffect(() => {
    if (location.pathname !== "/search") {
      setKeyword("");
    }
    loadList();
  }, [location.pathname, location.search]);

  usePrismHighlight([list]);

  return (
    <div>
      {list.map((v, k) => (
        <div className="articles" key={k}>
          <CArticle article={v} />
          <div className="border-t border-t-dashed border-t-[#dbdbdb] mt-5 pt-2.5 pb-2.5 text-right"></div>
        </div>
      ))}
      <Pagination page={page} pageTotal={pageTotal} onChange={changePage} />
    </div>
  );
}
