// src/components/CArticle.vue
<template>
    <div class="article" v-if="article">
        <div class="entry-title">
            <img class="avatar" src="../assets/images/avatar.jpg" alt="">
            <h2>
                <router-link :to="'/article/'+article.id" v-html="markHigh(article.title,$route.query.keyword)"></router-link>
            </h2>
            <div class="entry-meta">
                by&nbsp;{{article.user.nick_name}}&nbsp;&nbsp;/&nbsp;&nbsp;<a rel="category tag"
                                                                         title="查看 默认分类 中的全部文章"
                                                                         :href="'/categroy/'+article.cate.domain">{{article.cate.name}}</a>&nbsp;&nbsp;/&nbsp;&nbsp;{{article.created_at
                | formatDate('YYYY-MM-DD HH:mm')}}
            </div>
        </div>
        <div class="entry" v-html="article.content" v-highlight>
        </div>
    </div>
</template>

<script>
    export default {
        name: "CArticle",
        props: ["article"],
        methods: {
            markHigh(content,keyword) {
                if(keyword){
                    return content.replace(keyword, '<mark>' + keyword + '</mark>')
                }else{
                    return content
                }
            }
        }
    }
</script>

// web/src/components/CArticle.tsx
import { useEffect, useMemo, useRef } from "react";
import hljs from "highlight.js/lib/core";
import { Link, useLocation } from "react-router-dom";
export function CArticle({ article }: { article: any }) {
  const rootRef = useRef<HTMLDivElement>(null);
  const location = useLocation();
  const keyword = useMemo(
    () => new URLSearchParams(location.search).get("keyword") || "",
    [location.search]
  );
  const markHigh = (content: string, k: string) => {
    if (!k) return content;
    return content.replace(k, `<mark>${k}</mark>`);
  };
  useEffect(() => {
    const root = rootRef.current;
    if (!root) return;
    root.querySelectorAll("pre code").forEach((block) => {
      hljs.highlightElement(block as HTMLElement);
    });
  }, [article]);
  if (!article) return null;
  return (
    <div className="article" ref={rootRef}>
      <div className="entry-title">
        <img className="avatar" src="/assets/images/avatar.jpg" alt="" />
        <h2>
          <Link
            to={`/article/${article.id}`}
            dangerouslySetInnerHTML={{
              __html: markHigh(article.title, keyword),
            }}
          />
        </h2>
        <div className="entry-meta">
          by&nbsp;{article.user.nick_name}&nbsp;&nbsp;/&nbsp;&nbsp;
          <Link
            to={`/categroy/${article.cate.domain}`}
            rel="category tag"
            title={`查看 ${article.cate.name} 中的全部文章`}
          >
            {article.cate.name}
          </Link>
          &nbsp;&nbsp;/&nbsp;&nbsp;
          {article.created_at}
        </div>
      </div>
      <div
        className="entry"
        dangerouslySetInnerHTML={{ __html: article.content }}
      />
    </div>
  );
}
