// src/components/Mood.vue
<template>
    <div id="info">
        <div id="avatar"><img title="莫一哲" alt="莫一哲" src="../assets/images/faceicon.jpg"></div>
        <div id="latest">
            <p class="current active" v-if="moods[index]">
                {{moods[index].content}}
                <span class="stamp">
                <span class="method">{{moods[index].created_at | humanTime }} by {{moods[index].user.nick_name}}</span>
            </span>
            </p>
        </div>
        <div class="handle">
            <i class="iconfont icon-left" title="上一条" @click="prev"></i>
            <i class="iconfont icon-right" title="下一条" @click="next"></i>
        </div>
    </div>
</template>

<script>
  import {sync} from "../utils";
  import {moodListApi} from "../service";

  export default {
    name: 'Mood',
    data() {
      return {
        moods: [],
        index: 0
      }
    },
    methods: {
      prev() {
        let i = this.index - 1
        if (i >= 0) {
          this.index = i
        }
      },
      next() {
        let i = this.index + 1
        if (i < this.moods.length) {
          this.index = i
        }
      }
    },
    mounted() {
      sync(async () => {
        let ret = await moodListApi({page:1})
        this.moods = ret.list
        if (this.moods.length > 0) {
          this.current = this.moods[0]
        }
      })
    }
  }
</script>

// web/src/components/Mood.tsx
import { useEffect, useState } from "react";
import { moodListApi } from "@/service";
import dayjs from "dayjs";

function humanTime(v: string) {
  const currTime = dayjs().add(1, "second");
  const itemTime = dayjs(v);
  if (itemTime.isBetween(currTime.subtract(60, "second"), currTime)) {
    return currTime.diff(itemTime, "second") + "秒前";
  } else if (
    itemTime.isBetween(
      currTime.subtract(60, "minute"),
      currTime.subtract(1, "minute")
    )
  ) {
    return currTime.diff(itemTime, "minute") + "分钟前";
  } else if (
    itemTime.isBetween(currTime.startOf("day"), currTime.endOf("day"))
  ) {
    return "今天" + itemTime.format("HH:mm");
  } else if (
    itemTime.isBetween(
      currTime.subtract(1, "day").startOf("day"),
      currTime.subtract(1, "day").endOf("day")
    )
  ) {
    return "昨天" + itemTime.format("HH:mm");
  } else if (
    itemTime.isBetween(
      currTime.startOf("year"),
      currTime.subtract(1, "day").endOf("day")
    )
  ) {
    return itemTime.format("MM月DD日 HH:mm");
  } else {
    return itemTime.format("YYYY-MM-DD HH:mm");
  }
}

export function Mood() {
  const [moods, setMoods] = useState<any[]>([]);
  const [index, setIndex] = useState(0);
  useEffect(() => {
    (async () => {
      const ret = await moodListApi({ page: 1 });
      setMoods(ret.list || []);
    })();
  }, []);
  const prev = () => setIndex((i) => (i - 1 >= 0 ? i - 1 : i));
  const next = () => setIndex((i) => (i + 1 < moods.length ? i + 1 : i));
  const m = moods[index];
  return (
    <div id="info">
      <div id="avatar">
        <img title="莫一哲" alt="莫一哲" src="/assets/images/faceicon.jpg" />
      </div>
      <div id="latest">
        {m && (
          <p className="current active">
            {m.content}
            <span className="stamp">
              <span className="method">
                {humanTime(m.created_at)} by {m.user.nick_name}
              </span>
            </span>
          </p>
        )}
      </div>
      <div className="handle">
        <i className="iconfont icon-left" title="上一条" onClick={prev} />
        <i className="iconfont icon-right" title="下一条" onClick={next} />
      </div>
    </div>
  );
}
